color:
  brandStrength: 0.6143426
  saturation: 0.2707192
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.3209164
  rhythmicContrast: 0.2410595
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.5029493
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: Ashtanga
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5450391
