layout_spectrum: 0.5029493
typography_spectrum: 0.5450391
color:
  lightness: 0.3209164
  brandStrength: 0.6143426
  saturation: 0.2707192
  rhythmicContrast: 0.2410595
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Ashtanga
